#!/bin/bash

trap "echo Subcommand failed! script aborted.; exit 1" ERR
set -e
set -o pipefail

sudo apt-get update

PACKAGES="nano git screen htop build-essential python python3 jq"
for pkg in $PACKAGES; do
  output=$(sudo bash -c "dpkg -l ${pkg} &> /dev/null && echo installed")

  if [[ $output == "installed" ]]; then
    echo "$pkg is already installed."
  else
    sudo apt-get --assume-yes install $pkg
  fi
done

if [ -f /usr/local/go/bin/go ]; then
	echo "Go is already installed."
else
  install-go
fi
